"""
Infrastructure-announcement corpus.

In production this corpus would be populated by an ingestion pipeline scraping
NHAI / Indian Railways / AAI / RERA / PIB feeds. For the MVP it ships with a
curated set of representative announcements so the NLP signal parser has real
text to work on. Each entry is tagged with the city / state it concerns so
retrieval can be evaluated.
"""

CORPUS = [
    {"id": "sig_patna_ringroad", "city_id": "patna", "state": "Bihar", "year": 2024,
     "source": "NHAI",
     "text": "NHAI has approved the Rs 3,200 crore Patna Ring Road project. Tenders for the eastern arc have been awarded and construction begins next year, opening new residential corridors on the city fringe."},
    {"id": "sig_jhanjharpur_rail", "city_id": "jhanjharpur", "state": "Bihar", "year": 2024,
     "source": "Indian Railways",
     "text": "A new broad-gauge railway line connecting Jhanjharpur to Darbhanga has been sanctioned under the railway budget. Survey work is underway and land acquisition has been proposed for the junction."},
    {"id": "sig_darbhanga_airport", "city_id": "darbhanga", "state": "Bihar", "year": 2023,
     "source": "AAI",
     "text": "Darbhanga airport became operational with daily flights to Delhi and Mumbai. AAI announced a new terminal building and runway extension, inaugurated by the minister."},
    {"id": "sig_purnia_airport", "city_id": "purnia", "state": "Bihar", "year": 2024,
     "source": "AAI",
     "text": "Purnia greenfield airport land acquisition is completed and an AAI feasibility study cleared a Rs 450 crore terminal. The project is approved and detailed planning has begun."},
    {"id": "sig_tirupati_smartcity", "city_id": "tirupati", "state": "Andhra Pradesh", "year": 2023,
     "source": "Smart City Mission",
     "text": "Tirupati Smart City Mission allocated Rs 1,100 crore for road widening and an IT park near the airport corridor, with a command centre already operational."},
    {"id": "sig_warangal_textile", "city_id": "warangal", "state": "Telangana", "year": 2024,
     "source": "NICDC",
     "text": "Kakatiya Mega Textile Park near Warangal received central approval. NICDC notified an industrial corridor node expected to generate 30,000 jobs and trigger plotting along the access road."},
    {"id": "sig_raipur_expressway", "city_id": "raipur", "state": "Chhattisgarh", "year": 2024,
     "source": "NHAI",
     "text": "The Raipur to Visakhapatnam economic corridor (NH-130CD) is under construction. The six-lane expressway will cut travel time and is sanctioned at over Rs 18,000 crore across states."},
    {"id": "sig_bhubaneswar_metro", "city_id": "bhubaneswar", "state": "Odisha", "year": 2024,
     "source": "Metro Rail",
     "text": "Bhubaneswar metro rail DPR was approved. Phase-1 of 26 km is sanctioned at Rs 6,200 crore and tenders are to be floated this year."},
    {"id": "sig_siliguri_ringroad", "city_id": "siliguri", "state": "West Bengal", "year": 2023,
     "source": "NHIDCL",
     "text": "A Siliguri ring road and a new four-lane national highway bypass are proposed to decongest the Sevoke corridor. A detailed project report is under preparation."},
    {"id": "sig_kota_dme", "city_id": "kota", "state": "Rajasthan", "year": 2023,
     "source": "NHAI",
     "text": "The Delhi-Mumbai Expressway interchange near Kota was inaugurated, opening up industrial plotting and township layouts along the access road."},
    {"id": "sig_jamnagar_sez", "city_id": "jamnagar", "state": "Gujarat", "year": 2024,
     "source": "RERA",
     "text": "Jamnagar refinery expansion and a new SEZ were notified. RERA registrations in the city surged 40 percent year on year as residential demand rose."},
    {"id": "sig_indore_metro", "city_id": "indore", "state": "Madhya Pradesh", "year": 2024,
     "source": "Metro Rail",
     "text": "Indore metro completed a trial run on the 31 km super-priority corridor. Commercial operations are expected within a year and are under construction."},
    {"id": "sig_bhopal_corridor", "city_id": "bhopal", "state": "Madhya Pradesh", "year": 2024,
     "source": "NHAI",
     "text": "A Bhopal to Indore high-speed corridor is proposed. A pre-feasibility survey was commissioned by NHAI to evaluate the alignment."},
    {"id": "sig_lucknow_orr", "city_id": "lucknow", "state": "Uttar Pradesh", "year": 2023,
     "source": "NHAI",
     "text": "The Lucknow outer ring road is fully operational. AAI is expanding the Chaudhary Charan Singh airport with a new terminal that was approved last year."},
    {"id": "sig_varanasi_ropeway", "city_id": "varanasi", "state": "Uttar Pradesh", "year": 2024,
     "source": "Smart City Mission",
     "text": "The Varanasi ropeway project, India's first urban public transport ropeway, is under construction at Rs 650 crore and will ease movement in the old city."},
    {"id": "sig_gorakhpur_link", "city_id": "gorakhpur", "state": "Uttar Pradesh", "year": 2023,
     "source": "Expressways Authority",
     "text": "The Gorakhpur Link Expressway connecting to the Purvanchal Expressway was inaugurated, boosting industrial land demand along the route."},
    {"id": "sig_surat_metro", "city_id": "surat", "state": "Gujarat", "year": 2024,
     "source": "Metro Rail",
     "text": "Surat diamond bourse is operational and the Surat metro phase-1 is under construction, with two corridors totalling about 40 km approved."},
    {"id": "sig_vizag_capital", "city_id": "visakhapatnam", "state": "Andhra Pradesh", "year": 2024,
     "source": "State Government",
     "text": "Visakhapatnam was declared the executive capital. A new Rs 8,000 crore industrial park and the Bhogapuram greenfield airport are nearing completion."},
    {"id": "sig_ranchi_smartcity", "city_id": "ranchi", "state": "Jharkhand", "year": 2023,
     "source": "Smart City Mission",
     "text": "The Ranchi ring road phase was completed and an IT park and Smart City command centre were inaugurated, lifting demand for peripheral plots."},
    {"id": "sig_jamshedpur_gatishakti", "city_id": "jamshedpur", "state": "Jharkhand", "year": 2024,
     "source": "PM Gati Shakti",
     "text": "A Jamshedpur airport feasibility study was approved and an industrial cluster expansion is proposed under PM Gati Shakti to attract ancillary units."},
    {"id": "sig_guwahati_ringroad", "city_id": "guwahati", "state": "Assam", "year": 2024,
     "source": "NHIDCL",
     "text": "A Guwahati ring road and a new bridge over the Brahmaputra were sanctioned at Rs 3,000 crore under NHIDCL, with construction beginning soon."},
    {"id": "sig_nagpur_mihan", "city_id": "nagpur", "state": "Maharashtra", "year": 2023,
     "source": "MADC",
     "text": "Nagpur MIHAN multimodal hub was expanded and the Samruddhi Expressway to Mumbai is fully operational, accelerating warehousing and logistics land uptake."},
    {"id": "sig_coimbatore_metro", "city_id": "coimbatore", "state": "Tamil Nadu", "year": 2024,
     "source": "Metro Rail",
     "text": "A Coimbatore integrated bus terminus is operational and a proposed metro DPR was submitted. The airport runway extension was approved this year."},
    {"id": "sig_jodhpur_elevated", "city_id": "jodhpur", "state": "Rajasthan", "year": 2024,
     "source": "State PWD",
     "text": "A Jodhpur elevated road corridor is proposed and a regional ring road survey was commissioned this year to guide future land use."},
    {"id": "sig_bihar_industrial", "city_id": None, "state": "Bihar", "year": 2024,
     "source": "State Investment Board",
     "text": "The Bihar government notified four new industrial zones under the state investment policy. AMRUT 2.0 funds were released for ten Tier-3 towns for water and road upgrades."},
    {"id": "sig_up_defence", "city_id": None, "state": "Uttar Pradesh", "year": 2023,
     "source": "State Government",
     "text": "Uttar Pradesh's Defence Industrial Corridor nodes attracted fresh investment and the state expressway network expansion continues across districts."},
]
